### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by SuperKB24** [rex-chien/taiwan-2020-election-hustings#2]
when i run the file,i meet a problem.

  D:\Anaconda3\envs\tensorflow\python.exe  D:/Downloads/taiwan-2020-election-hustings/main.py
  File "D:/Downloads/taiwan-2020-election-hustings/main.py", line 64
    output_file_path = os.path.join(dirname, f'{file_name}_tf.dat')
                                                                 ^
 SyntaxError: invalid syntax

**Comment by rex-chien** [comment]
Which version of python are you using?

**Comment by SuperKB24** [comment]
hello,i use the python3.5.because I failed to install tensorflow with the higher version of python
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rex.Chien"<notifications@github.com&gt;; 
发送时间: 2020年3月22日(星期天) 晚上11:23
收件人: "rex-chien/taiwan-2020-election-hustings"<taiwan-2020-election-hustings@noreply.github.com&gt;; 
抄送: "≮梦★羽≯"<576288142@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rex-chien/taiwan-2020-election-hustings] SyntaxError (#2)





 
Which version of python are you using?

**Comment by rex-chien** [comment]
This error is caused by `f-string`, or [PEP 498](https://www.python.org/dev/peps/pep-0498/), which needs python 3.6 or higher.

**Comment by SuperKB24** [comment]
thanks，i will try it later



---Original---
