### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SuperKB24** [rex-chien/taiwan-2020-election-hustings#3]
Hello,this time i installed tensorflow1.13.1 with python3.7 successfully.But when i run the file,there is no
output.Could  you give me a hand?
![7 7OXR)Q63M0~W S)U3%PYS](https://user-images.githubusercontent.com/62506425/77295191-70f97880-6d20-11ea-8bb5-7180b8babf7a.png)

**Comment by rex-chien** [comment]
Have you checked transcripts source directory? Output file would be generated to the same directory where transcripts text files located.

**Comment by SuperKB24** [comment]
Yes,i checked.There is nothing new.
![image](https://user-images.githubusercontent.com/62506425/77297063-b79ca200-6d23-11ea-99b7-0c7acbf66bdb.png)

**Comment by SuperKB24** [comment]
Yes,i checked the same dirctory,but there is nothing new.
![BF DD W3R_ LI~$@}Y9(O](https://user-images.githubusercontent.com/62506425/77297255-f7fc2000-6d23-11ea-8fed-c467c41db07c.png)

**Comment by rex-chien** [comment]
If you run this [main.py](https://github.com/rex-chien/taiwan-2020-election-hustings/blob/master/main.py), which read text files in `./transcripts/2019-12-29-president-debate`, the output files would be generated to `./transcripts/2019-12-29-president-debate` directory.

**Comment by SuperKB24** [comment]
Yes,i found it.Thank you so much for your help.
